#!/usr/bin/env python3
"""Regenerate src/lib/og/glyphs.ts: outlines + advances for the share cards.

The Vercel function has no system fonts, so card text is drawn as vector paths.
Source faces (SIL OFL, static instances served by Google Fonts):
  serif = Fraunces 600, sans = Manrope 500, bold = Manrope 700.

  pip install fonttools
  python3 scripts/build-og-glyphs.py
"""
import io
import json
import re
import urllib.request

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

CSS = "https://fonts.googleapis.com/css2?family=Fraunces:wght@600&family=Manrope:wght@500;700"
CHARS = (
    [chr(c) for c in range(0x20, 0x7F)]
    + [chr(c) for c in range(0xA1, 0x100)]
    + list("‘’“”…–—•·€ŒœŁłı")
)


def fetch(url, ua="Mozilla/4.0"):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": ua})).read()


def face(data):
    font = TTFont(io.BytesIO(data))
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    out = {"upm": font["head"].unitsPerEm, "adv": {}, "d": {}}
    for ch in CHARS:
        name = cmap.get(ord(ch))
        if not name:
            continue
        pen = SVGPathPen(gs, ntos=lambda v: str(int(round(v))))
        gs[name].draw(pen)
        out["adv"][ch] = gs[name].width
        d = pen.getCommands()
        if d:
            out["d"][ch] = d
    return out


css = fetch(CSS).decode()
urls = re.findall(r"url\((https://[^)]+\.ttf)\)", css)
by_family = {}
for block in css.split("@font-face")[1:]:
    fam = re.search(r"font-family: '([^']+)'", block).group(1)
    wt = re.search(r"font-weight: (\d+)", block).group(1)
    by_family[(fam, wt)] = re.search(r"url\((https://[^)]+\.ttf)\)", block).group(1)

faces = {
    "serif": face(fetch(by_family[("Fraunces", "600")])),
    "sans": face(fetch(by_family[("Manrope", "500")])),
    "bold": face(fetch(by_family[("Manrope", "700")])),
}
with open("src/lib/og/glyphs.ts", "w") as fh:
    fh.write("/** Generated by scripts/build-og-glyphs.py. Fraunces 600, Manrope 500/700 (SIL OFL). Do not edit. */\n")
    fh.write("export type GlyphFace = { upm: number; adv: Record<string, number>; d: Record<string, string> };\n")
    fh.write("export const GLYPHS: Record<\"serif\" | \"sans\" | \"bold\", GlyphFace> = ")
    fh.write(json.dumps(faces, ensure_ascii=False, separators=(",", ":")))
    fh.write(";\n")
