/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DenylistRouteImport } from './routes/denylist'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as MethodRouteImport } from './routes/method'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as MysteriesRouteImport } from './routes/mysteries'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as OgSplatRouteImport } from './routes/og/$'
import { Route as ApiV1DeltasRouteImport } from './routes/api/v1/deltas'
import { Route as ApiV1LeaderboardRouteImport } from './routes/api/v1/leaderboard'
import { Route as ApiV1ExportCompaniesRouteImport } from './routes/api/v1/export/companies'
import { Route as ApiV1ExportSnapshotsRouteImport } from './routes/api/v1/export/snapshots'
import { Route as ApiV1ExportSponsorshipsRouteImport } from './routes/api/v1/export/sponsorships'
import { Route as ApiV1GraphCoSponsorshipsRouteImport } from './routes/api/v1/graph/co-sponsorships'
import { Route as ApiV1WatchlistIndexRouteImport } from './routes/api/v1/watchlist/index'
import { Route as ApiV1WatchlistAlertsRouteImport } from './routes/api/v1/watchlist/alerts'
import { Route as ApiV1CompaniesSlugIndexRouteImport } from './routes/api/v1/companies/$slug/index'
import { Route as ApiV1CompaniesSlugSponsorshipsRouteImport } from './routes/api/v1/companies/$slug/sponsorships'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenylistRoute = DenylistRouteImport.update({
  id: '/denylist',
  path: '/denylist',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const MysteriesRoute = MysteriesRouteImport.update({
  id: '/mysteries',
  path: '/mysteries',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeltasRoute = ApiV1DeltasRouteImport.update({
  id: '/api/v1/deltas',
  path: '/api/v1/deltas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LeaderboardRoute = ApiV1LeaderboardRouteImport.update({
  id: '/api/v1/leaderboard',
  path: '/api/v1/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportCompaniesRoute = ApiV1ExportCompaniesRouteImport.update({
  id: '/api/v1/export/companies',
  path: '/api/v1/export/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportSnapshotsRoute = ApiV1ExportSnapshotsRouteImport.update({
  id: '/api/v1/export/snapshots',
  path: '/api/v1/export/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportSponsorshipsRoute = ApiV1ExportSponsorshipsRouteImport.update({
  id: '/api/v1/export/sponsorships',
  path: '/api/v1/export/sponsorships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GraphCoSponsorshipsRoute =
  ApiV1GraphCoSponsorshipsRouteImport.update({
    id: '/api/v1/graph/co-sponsorships',
    path: '/api/v1/graph/co-sponsorships',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WatchlistIndexRoute = ApiV1WatchlistIndexRouteImport.update({
  id: '/api/v1/watchlist/',
  path: '/api/v1/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WatchlistAlertsRoute = ApiV1WatchlistAlertsRouteImport.update({
  id: '/api/v1/watchlist/alerts',
  path: '/api/v1/watchlist/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompaniesSlugIndexRoute = ApiV1CompaniesSlugIndexRouteImport.update({
  id: '/api/v1/companies/$slug/',
  path: '/api/v1/companies/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompaniesSlugSponsorshipsRoute =
  ApiV1CompaniesSlugSponsorshipsRouteImport.update({
    id: '/api/v1/companies/$slug/sponsorships',
    path: '/api/v1/companies/$slug/sponsorships',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denylist': typeof DenylistRoute
  '/graph': typeof GraphRoute
  '/method': typeof MethodRoute
  '/movements': typeof MovementsRoute
  '/mysteries': typeof MysteriesRoute
  '/ranking': typeof RankingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/health': typeof ApiHealthRoute
  '/company/$slug': typeof CompanySlugRoute
  '/og/$': typeof OgSplatRoute
  '/api/v1/deltas': typeof ApiV1DeltasRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/export/companies': typeof ApiV1ExportCompaniesRoute
  '/api/v1/export/snapshots': typeof ApiV1ExportSnapshotsRoute
  '/api/v1/export/sponsorships': typeof ApiV1ExportSponsorshipsRoute
  '/api/v1/graph/co-sponsorships': typeof ApiV1GraphCoSponsorshipsRoute
  '/api/v1/watchlist/alerts': typeof ApiV1WatchlistAlertsRoute
  '/api/v1/watchlist/': typeof ApiV1WatchlistIndexRoute
  '/api/v1/companies/$slug/sponsorships': typeof ApiV1CompaniesSlugSponsorshipsRoute
  '/api/v1/companies/$slug/': typeof ApiV1CompaniesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denylist': typeof DenylistRoute
  '/graph': typeof GraphRoute
  '/method': typeof MethodRoute
  '/movements': typeof MovementsRoute
  '/mysteries': typeof MysteriesRoute
  '/ranking': typeof RankingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/health': typeof ApiHealthRoute
  '/company/$slug': typeof CompanySlugRoute
  '/og/$': typeof OgSplatRoute
  '/api/v1/deltas': typeof ApiV1DeltasRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/export/companies': typeof ApiV1ExportCompaniesRoute
  '/api/v1/export/snapshots': typeof ApiV1ExportSnapshotsRoute
  '/api/v1/export/sponsorships': typeof ApiV1ExportSponsorshipsRoute
  '/api/v1/graph/co-sponsorships': typeof ApiV1GraphCoSponsorshipsRoute
  '/api/v1/watchlist/alerts': typeof ApiV1WatchlistAlertsRoute
  '/api/v1/watchlist': typeof ApiV1WatchlistIndexRoute
  '/api/v1/companies/$slug/sponsorships': typeof ApiV1CompaniesSlugSponsorshipsRoute
  '/api/v1/companies/$slug': typeof ApiV1CompaniesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/denylist': typeof DenylistRoute
  '/graph': typeof GraphRoute
  '/method': typeof MethodRoute
  '/movements': typeof MovementsRoute
  '/mysteries': typeof MysteriesRoute
  '/ranking': typeof RankingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/health': typeof ApiHealthRoute
  '/company/$slug': typeof CompanySlugRoute
  '/og/$': typeof OgSplatRoute
  '/api/v1/deltas': typeof ApiV1DeltasRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/export/companies': typeof ApiV1ExportCompaniesRoute
  '/api/v1/export/snapshots': typeof ApiV1ExportSnapshotsRoute
  '/api/v1/export/sponsorships': typeof ApiV1ExportSponsorshipsRoute
  '/api/v1/graph/co-sponsorships': typeof ApiV1GraphCoSponsorshipsRoute
  '/api/v1/watchlist/alerts': typeof ApiV1WatchlistAlertsRoute
  '/api/v1/watchlist/': typeof ApiV1WatchlistIndexRoute
  '/api/v1/companies/$slug/sponsorships': typeof ApiV1CompaniesSlugSponsorshipsRoute
  '/api/v1/companies/$slug/': typeof ApiV1CompaniesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denylist'
    | '/graph'
    | '/method'
    | '/movements'
    | '/mysteries'
    | '/ranking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/watchlist'
    | '/api/health'
    | '/company/$slug'
    | '/og/$'
    | '/api/v1/deltas'
    | '/api/v1/leaderboard'
    | '/api/v1/export/companies'
    | '/api/v1/export/snapshots'
    | '/api/v1/export/sponsorships'
    | '/api/v1/graph/co-sponsorships'
    | '/api/v1/watchlist/alerts'
    | '/api/v1/watchlist/'
    | '/api/v1/companies/$slug/sponsorships'
    | '/api/v1/companies/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denylist'
    | '/graph'
    | '/method'
    | '/movements'
    | '/mysteries'
    | '/ranking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/watchlist'
    | '/api/health'
    | '/company/$slug'
    | '/og/$'
    | '/api/v1/deltas'
    | '/api/v1/leaderboard'
    | '/api/v1/export/companies'
    | '/api/v1/export/snapshots'
    | '/api/v1/export/sponsorships'
    | '/api/v1/graph/co-sponsorships'
    | '/api/v1/watchlist/alerts'
    | '/api/v1/watchlist'
    | '/api/v1/companies/$slug/sponsorships'
    | '/api/v1/companies/$slug'
  id:
    | '__root__'
    | '/'
    | '/denylist'
    | '/graph'
    | '/method'
    | '/movements'
    | '/mysteries'
    | '/ranking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/watchlist'
    | '/api/health'
    | '/company/$slug'
    | '/og/$'
    | '/api/v1/deltas'
    | '/api/v1/leaderboard'
    | '/api/v1/export/companies'
    | '/api/v1/export/snapshots'
    | '/api/v1/export/sponsorships'
    | '/api/v1/graph/co-sponsorships'
    | '/api/v1/watchlist/alerts'
    | '/api/v1/watchlist/'
    | '/api/v1/companies/$slug/sponsorships'
    | '/api/v1/companies/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DenylistRoute: typeof DenylistRoute
  GraphRoute: typeof GraphRoute
  MethodRoute: typeof MethodRoute
  MovementsRoute: typeof MovementsRoute
  MysteriesRoute: typeof MysteriesRoute
  RankingRoute: typeof RankingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CompanySlugRoute: typeof CompanySlugRoute
  OgSplatRoute: typeof OgSplatRoute
  ApiV1DeltasRoute: typeof ApiV1DeltasRoute
  ApiV1LeaderboardRoute: typeof ApiV1LeaderboardRoute
  ApiV1ExportCompaniesRoute: typeof ApiV1ExportCompaniesRoute
  ApiV1ExportSnapshotsRoute: typeof ApiV1ExportSnapshotsRoute
  ApiV1ExportSponsorshipsRoute: typeof ApiV1ExportSponsorshipsRoute
  ApiV1GraphCoSponsorshipsRoute: typeof ApiV1GraphCoSponsorshipsRoute
  ApiV1WatchlistAlertsRoute: typeof ApiV1WatchlistAlertsRoute
  ApiV1WatchlistIndexRoute: typeof ApiV1WatchlistIndexRoute
  ApiV1CompaniesSlugSponsorshipsRoute: typeof ApiV1CompaniesSlugSponsorshipsRoute
  ApiV1CompaniesSlugIndexRoute: typeof ApiV1CompaniesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denylist': {
      id: '/denylist'
      path: '/denylist'
      fullPath: '/denylist'
      preLoaderRoute: typeof DenylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mysteries': {
      id: '/mysteries'
      path: '/mysteries'
      fullPath: '/mysteries'
      preLoaderRoute: typeof MysteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deltas': {
      id: '/api/v1/deltas'
      path: '/api/v1/deltas'
      fullPath: '/api/v1/deltas'
      preLoaderRoute: typeof ApiV1DeltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/leaderboard': {
      id: '/api/v1/leaderboard'
      path: '/api/v1/leaderboard'
      fullPath: '/api/v1/leaderboard'
      preLoaderRoute: typeof ApiV1LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export/companies': {
      id: '/api/v1/export/companies'
      path: '/api/v1/export/companies'
      fullPath: '/api/v1/export/companies'
      preLoaderRoute: typeof ApiV1ExportCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export/snapshots': {
      id: '/api/v1/export/snapshots'
      path: '/api/v1/export/snapshots'
      fullPath: '/api/v1/export/snapshots'
      preLoaderRoute: typeof ApiV1ExportSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export/sponsorships': {
      id: '/api/v1/export/sponsorships'
      path: '/api/v1/export/sponsorships'
      fullPath: '/api/v1/export/sponsorships'
      preLoaderRoute: typeof ApiV1ExportSponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/graph/co-sponsorships': {
      id: '/api/v1/graph/co-sponsorships'
      path: '/api/v1/graph/co-sponsorships'
      fullPath: '/api/v1/graph/co-sponsorships'
      preLoaderRoute: typeof ApiV1GraphCoSponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/watchlist/': {
      id: '/api/v1/watchlist/'
      path: '/api/v1/watchlist'
      fullPath: '/api/v1/watchlist/'
      preLoaderRoute: typeof ApiV1WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/watchlist/alerts': {
      id: '/api/v1/watchlist/alerts'
      path: '/api/v1/watchlist/alerts'
      fullPath: '/api/v1/watchlist/alerts'
      preLoaderRoute: typeof ApiV1WatchlistAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/companies/$slug/': {
      id: '/api/v1/companies/$slug/'
      path: '/api/v1/companies/$slug'
      fullPath: '/api/v1/companies/$slug/'
      preLoaderRoute: typeof ApiV1CompaniesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/companies/$slug/sponsorships': {
      id: '/api/v1/companies/$slug/sponsorships'
      path: '/api/v1/companies/$slug/sponsorships'
      fullPath: '/api/v1/companies/$slug/sponsorships'
      preLoaderRoute: typeof ApiV1CompaniesSlugSponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DenylistRoute: DenylistRoute,
  GraphRoute: GraphRoute,
  MethodRoute: MethodRoute,
  MovementsRoute: MovementsRoute,
  MysteriesRoute: MysteriesRoute,
  RankingRoute: RankingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchlistRoute: WatchlistRoute,
  ApiHealthRoute: ApiHealthRoute,
  CompanySlugRoute: CompanySlugRoute,
  OgSplatRoute: OgSplatRoute,
  ApiV1DeltasRoute: ApiV1DeltasRoute,
  ApiV1LeaderboardRoute: ApiV1LeaderboardRoute,
  ApiV1ExportCompaniesRoute: ApiV1ExportCompaniesRoute,
  ApiV1ExportSnapshotsRoute: ApiV1ExportSnapshotsRoute,
  ApiV1ExportSponsorshipsRoute: ApiV1ExportSponsorshipsRoute,
  ApiV1GraphCoSponsorshipsRoute: ApiV1GraphCoSponsorshipsRoute,
  ApiV1WatchlistAlertsRoute: ApiV1WatchlistAlertsRoute,
  ApiV1WatchlistIndexRoute: ApiV1WatchlistIndexRoute,
  ApiV1CompaniesSlugSponsorshipsRoute: ApiV1CompaniesSlugSponsorshipsRoute,
  ApiV1CompaniesSlugIndexRoute: ApiV1CompaniesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
